name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Build
        run: |
          ./gradlew build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          # Configuring release name and tag.
          name: Build \#${{ github.run_number }}
          tag_name: ${{ github.run_number }}
          # Configuring files that are attached to the release.
          files: "build/libs/LuaStubGen-1.0-SNAPSHOT.jar"

