name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Build and Publish to Modrinth
        run: |
          ./gradlew build
      - name: Create a Release
        uses: elgohr/Github-Release-Action@c5ea99036abb741a89f8bf1f2cd7fba845e3313a # v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Build ${{ github.run_number }}
          tag: ${{ github.run_number }}
          workdir: ./build/libs/

